openapi: 3.0.0
info:
  title: ena-rpa
  version: '1.0'
  description: 恵那市　音声告知機 RPA用API
  contact:
    name: masashi mizuno
    url: 'https://goldkey.co.jp'
    email: m-mizuno@goldkey.co.jp
servers:
  - url: 'http://127.0.0.1:3100'
paths:
  /schedule:
    get:
      summary: スケジュール
      tags:
        - schedule
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleListModel'
              examples:
                example:
                  value:
                    - id: 1
                      name: ラグビーW杯の全貌
                      on_air_date: '2019-10-28 10:10'
                      area: '三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町'
                      status: 1
                    - id: 2
                      name: カーペンダーズは女性グルー
                      on_air_date: '2019-10-28 10:10'
                      area: '三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町'
                      status: 2
                    - id: 3
                      name: 恵那市様の放送
                      on_air_date: '2019-10-28 10:10'
                      area: '三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町'
                      status: 3
                    - id: 4
                      name: 恵那市様の放送3
                      on_air_date: '2019-10-28 10:10'
                      area: '三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町'
                      status: 1
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: スケジュール一覧
      operationId: '001'
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: 放送名
        - schema:
            type: string
          in: query
          name: area
          description: エリア
    post:
      summary: ''
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: スケジュール追加・編集
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchedulePostlModel'
      operationId: '002'
      tags:
        - schedule
  /schedule/copy:
    post:
      summary: スケジュールコピー
      tags:
        - schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDetaillModel'
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: スケジュールコピー
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  description: コピーもとスケジュールID
              required:
                - id
      operationId: '003'
    x-tags:
      - schedule
  '/schedule/{id}':
    get:
      summary: スケジュール詳細
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDetaillModel'
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      operationId: '004'
      description: スケジュール詳細
      parameters: []
      tags:
        - schedule
    delete:
      summary: スケジュール削除
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDeleteModel'
      description: スケジュール削除
      operationId: '005'
      tags:
        - schedule
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
  /file:
    get:
      summary: 放送ファイル一覧
      tags:
        - file
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileListModel'
              examples:
                example:
                  value:
                    - id: 1
                      file_name: 'file_1.wav'
                      file_path: 'https://opengameart.org/sites/default/files/bodyimpact_jack_01.wav'
                      modified_date: '2019-10-28 10:10'
                      is_use: false
                    - id: 2
                      file_name: 'file_2.wav'
                      file_path: 'https://opengameart.org/sites/default/files/boing_jack_01.wav'
                      modified_date: '2019-10-28 10:10'
                      is_use: true
                    - id: 3
                      file_name: 'file_3.wav'
                      file_path: 'https://opengameart.org/sites/default/files/death_jack_02.wav'
                      modified_date: '2019-10-28 10:10'
                      is_use: false
                    - id: 4
                      file_name: 'file_4.wav'
                      file_path: 'https://opengameart.org/sites/default/files/get_armour.wav'
                      modified_date: '2019-10-28 10:10'
                      is_use: false
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: 放送ファイル一覧
      operationId: '006'
  /file/rename:
    post:
      summary: ファイル名変更
      tags:
        - file
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      operationId: '007'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileRenamePostModel'
      description: ファイル名変更
    parameters: []
  '/file/{id}':
    delete:
      summary: ファイル削除
      tags:
        - file
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      operationId: 8
      description: ファイル削除
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /speech/type:
    get:
      summary: 声色一覧
      tags:
        - speech
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpeechTypeListModel'
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: 声色一覧
      operationId: 9
  /speech/create:
    post:
      summary: 音声合成
      tags:
        - speech
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeechCreateModel'
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      operationId: '010'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpeechCreatePostModel'
      description: 音声合成
  /speech/publish:
    post:
      summary: 放送登録
      tags:
        - speech
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpeechPublishModel'
      description: 放送登録
      operationId: '0011'
  /status:
    get:
      summary: システム状況確認
      tags:
        - status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusModel'
              examples:
                Connected:
                  value:
                    status: 1
                    message: ''
                Disconnected:
                  value:
                    status: 2
                    message: ''
                Initializing:
                  value:
                    status: 3
                    message: ''
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: システム状況確認API
      operationId: '0012'
  /areas:
    get:
      summary: 放送範囲
      tags:
        - areas
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreasListModel'
              examples:
                example:
                  value:
                    - name: 東野
                      zones:
                        - id: 1
                          name: 武並長
                        - id: 2
                          name: 三郷町
                    - name: 中野方町
                      zones:
                        - id: 1
                          name: 飯地町
                        - id: 2
                          name: 岩村町
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
            Access-Control-Allow-Method:
              $ref: '#/components/headers/Access-Control-Allow-Method'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/Access-Control-Allow-Headers'
      description: 放送範囲一覧
      operationId: '013'
components:
  schemas:
    ScheduleListModel:
      title: ScheduleListModel
      type: object
      x-tags:
        - models
      x-examples:
        Example:
          id: 1
          name: ラグビーW杯の全貌
          on_air_date: '2019-10-28 10:10'
          area: '三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町,三郷町'
          status: 1
      properties:
        id:
          type: integer
        status:
          type: integer
          enum:
            - 定期放送
            - 待ち
            - １回
          description: '状態（1: 定期放送、2: 待ち、3: １回）'
        area:
          type: string
        on_air_date:
          type: string
        name:
          type: string
      required:
        - id
        - status
        - area
        - on_air_date
        - name
    SchedulePostlModel:
      title: SchedulePostModel
      type: object
      description: ''
      properties:
        id:
          type: number
          description: idはoptional あれば編集、なければ新規
        name:
          type: string
          description: 放送名
        mode:
          type: string
          description: モード
        priority:
          type: number
          description: 優先度
        start_sound:
          type: number
          description: 開始チャイム
        end_sound:
          type: number
          description: 終了チャイム
        reservation_datetime:
          type: string
          description: |-
            予約放送時のみ
            放送時間
        reservation_start_date:
          type: string
          description: |-
            定期放送のみ
            定期放送開始日
        reservation_end_date:
          type: string
          description: |-
            定期放送のみ
            定期放送終了日
        reservation_repeat_type:
          type: number
          description: |-
            定期放送のみ
            繰り返し周期
        reservation_repeat_time:
          type: string
          description: |-
            定期放送のみ
            放送開始時間
        on_air_flag:
          type: number
          description: 放送フラグ
        conflict:
          type: number
          description: 衝突時
        interrupt:
          type: number
          description: 被割込み時
        files:
          type: string
          description: 音声ファイルバイナリデータ
        on_air_areas:
          type: array
          description: |
            放送エリア
          items:
            type: object
            properties:
              id:
                type: number
                description: エリアID
            required:
              - id
        on_air_mode:
          type: number
          description: |-
            放送モード
            即時・予約・定期
      required:
        - name
        - mode
        - priority
        - start_sound
        - end_sound
        - on_air_flag
        - conflict
        - interrupt
        - files
        - on_air_areas
      x-tags:
        - models
    ScheduleDetaillModel:
      title: ScheduleDetailModel
      type: object
      description: ''
      x-examples: {}
      properties:
        name:
          type: string
          description: 放送名
        mode:
          type: string
          description: モード
        priority:
          type: number
          description: 優先度
        start_sound:
          type: number
          description: 開始チャイム
        end_sound:
          type: number
          description: 終了チャイム
        reservation_datetime:
          type: string
          description: |-
            予約放送時のみ
            放送時間
        reservation_start_date:
          type: string
          description: |-
            定期放送のみ
            定期放送開始日
        reservation_end_date:
          type: string
          description: |-
            定期放送のみ
            定期放送終了日
        reservation_repeat_type:
          type: number
          description: |-
            定期放送のみ
            繰り返し周期
        reservation_repeat_time:
          type: string
          description: |-
            定期放送のみ
            放送開始時間
        on_air_flag:
          type: number
          description: 放送フラグ
        conflict:
          type: number
          description: 衝突時
        interrupt:
          type: number
          description: 被割込み時
        files:
          type: array
          description: 音声ファイルバイナリデータ
          items:
            type: object
            properties:
              name:
                type: string
                description: ファイル名
              file_path:
                type: string
                description: ファイルパス
            required:
              - name
              - file_path
        on_air_areas:
          type: array
          description: |
            放送エリア
          items:
            type: object
            properties:
              id:
                type: number
                description: エリアID
            required:
              - id
        on_air_mode:
          type: number
          description: |-
            放送モード
            即時・予約・定期
      required:
        - name
        - mode
        - priority
        - start_sound
        - end_sound
        - on_air_flag
        - conflict
        - interrupt
        - files
        - on_air_areas
      x-tags:
        - models
    ScheduleDeleteModel:
      title: ScheduleDetailModel
      type: object
      description: ''
      x-examples:
        Example:
          message: Deleted
      properties:
        message:
          type: string
          description: response message
    FileListModel:
      title: FileListModel
      type: object
      x-tags:
        - models
      properties:
        id:
          type: number
        file_name:
          type: string
        file_path:
          type: string
        file_duration:
          type: integer
          description: 再生時間（秒数）
        modified_date:
          type: string
        is_use:
          type: boolean
          description: 放送に使用されているかどうか
      required:
        - id
        - file_name
        - file_path
        - file_duration
        - modified_date
        - is_use
    FileRenamePostModel:
      title: FileRenamePostModel
      type: object
      properties:
        id:
          type: number
        name:
          type: string
      required:
        - id
        - name
      x-tags:
        - models
    SpeechTypeListModel:
      title: SpeechTypeListModel
      type: object
      properties:
        id:
          type: array
          items: {}
        name:
          type: string
      required:
        - id
        - name
      x-tags:
        - models
    SpeechCreateModel:
      title: SpeechCreateModel
      type: object
      properties:
        temp_id:
          type: number
        file_path:
          type: string
        pitch:
          type: number
        speed:
          type: number
        wait:
          type: number
      required:
        - temp_id
        - volume
        - pitch
        - speed
        - wait
      x-tags:
        - models
    SpeechCreatePostModel:
      title: SpeechCreatePotsModel
      type: object
      properties:
        type:
          type: number
        volume:
          type: number
        pitch:
          type: number
        speed:
          type: number
        wait:
          type: number
      required:
        - type
        - volume
        - pitch
        - speed
        - wait
      x-tags:
        - models
    SpeechPublishModel:
      title: SpeechPublishModel
      type: object
      x-tags:
        - speech
      properties:
        temp_id:
          type: number
        file_name:
          type: string
        save_only:
          type: boolean
      required:
        - temp_id
        - file_name
        - save_only
    StatusModel:
      title: StatusModel
      type: object
      description: システム状況確認API
      properties:
        status:
          type: number
          description: 状態（１：接続中、２：切断中、３：初期化中）
          enum:
            - 1
            - 2
            - 3
        message:
          type: string
          description: メッセージ
    AreasListModel:
      title: AreasListModel
      type: object
      x-tags:
        - models
      x-examples:
        Example:
          id: 1
          name: 恵那市
      properties:
        name:
          type: string
        zones:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
              - id
              - name
      required:
        - name
        - zones
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
  headers:
    Access-Control-Allow-Origin:
      description: CORS settings
      example: '*'
      schema:
        type: string
    Access-Control-Allow-Method:
      description: CORS settings
      example: 'GET, POST, DELETE, HEAD'
      schema:
        type: string
    Access-Control-Allow-Headers:
      description: CORS settings
      example: 'Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token'
      schema:
        type: string
tags:
  - name: schedule
    description: スケジュール関連API
  - name: file
    description: ファイル関連API
  - name: speech
    description: RPA関連API
  - name: status
    description: API状況関連API
  - name: areas
    description: 放送範囲関連API
